# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_geom <- function(x, from, to, r) {
    .Call('_regclean_c_geom', PACKAGE = 'regclean', x, from, to, r)
}

